#!/usr/bin/env python3
"""
PSVT:R Cube Visualization - QOR-Inspired Edition

Uses:
- apply_rotation_via_query/13 for normal cube rotations
- apply_in_plane_rotation_full/13 for in-plane rotations

Only supported in-plane rotations here:
- 1q
- -1q
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import Rectangle
import subprocess
import re
from pathlib import Path
import os


# ============================================================================
# CONFIG
# ============================================================================

PROLOG_DIR = Path(__file__).resolve().parent
ROTATION_PROLOG_FILE = 'rotation_qor_inspired.pl'
Q3D_PROLOG_FILE = 'q3d-ex.pl'


# ============================================================================
# COLOR CONFIG
# ============================================================================

DEPTH_COLORS = {
    'a': '#90EE90',
    'b': '#FFD700',
    'c': '#FF6B6B',
    'd': '#4169E1',
    'e': '#8B008B',
    '*': '#CCCCCC',
}

DEPTH_LABELS = {
    'a': 'Depth A',
    'b': 'Depth B',
    'c': 'Depth C',
    'd': 'Depth D',
    'e': 'Depth E',
    '*': 'Occluded',
}


# ============================================================================
# PROLOG HELPERS
# ============================================================================

def query_prolog(query):
    """Execute a Prolog query and return stdout."""
    try:
        result = subprocess.run(
            ['swipl', '-q', '-t', 'halt'],
            input=query.encode(),
            capture_output=True,
            timeout=10,
            cwd=str(PROLOG_DIR)
        )

        stderr = result.stderr.decode().strip()
        if stderr:
            print("Prolog stderr:")
            print(stderr)

        return result.stdout.decode().strip()

    except Exception as e:
        print(f"Prolog error: {e}")
        return ""


def matrix_to_prolog(mat):
    """Convert Python matrix to Prolog list notation."""
    rows = []

    for row in mat:
        cells = []

        for cell in row:
            if isinstance(cell, str):
                if cell == '*':
                    cells.append("'*'")
                else:
                    cells.append(f"'{cell}'")
            else:
                cells.append(str(cell))

        rows.append('[' + ','.join(cells) + ']')

    return '[' + ','.join(rows) + ']'


def parse_prolog_matrix(prolog_str):
    """
    Parse Prolog matrix notation like:

    [[a,b,c],[d,e,f],[g,h,i]]

    into Python list of lists.
    """
    try:
        lines = [line.strip() for line in prolog_str.splitlines() if line.strip()]

        matrix_line = None

        for line in reversed(lines):
            if line.startswith('[[') and line.endswith(']]'):
                matrix_line = line
                break

        if matrix_line is None:
            text = prolog_str.strip()
            if text.startswith('[[') and text.endswith(']]'):
                matrix_line = text
            else:
                return None

        content = matrix_line.strip()

        if content.startswith('[['):
            content = content[2:]

        if content.endswith(']]'):
            content = content[:-2]

        row_strings = re.split(r'\],\s*\[', content)

        matrix = []

        for row_str in row_strings:
            row_str = row_str.replace('[', '').replace(']', '')
            cells = []

            for cell in row_str.split(','):
                cell = cell.strip().strip("'").strip('"')
                cells.append(cell)

            matrix.append(cells)

        return matrix

    except Exception as e:
        print(f"Error parsing Prolog matrix: {e}")
        return None


def parse_faces_from_write_result(output):
    """
    Parse output generated by Prolog write_result/6.

    Expected format:

    RESULT:
    FRONT:
    [[...]]
    BACK:
    [[...]]
    LEFT:
    [[...]]
    RIGHT:
    [[...]]
    UP:
    [[...]]
    DOWN:
    [[...]]
    """
    if 'RESULT:' not in output:
        return None

    lines = output.splitlines()
    faces_data = {}
    current_face = None
    matrix_lines = []

    for line in lines:
        line_stripped = line.strip()

        if line_stripped in ['FRONT:', 'BACK:', 'LEFT:', 'RIGHT:', 'UP:', 'DOWN:']:
            if current_face and matrix_lines:
                matrix_str = ''.join(matrix_lines)
                parsed = parse_prolog_matrix(matrix_str)

                if parsed:
                    faces_data[current_face] = parsed

            current_face = line_stripped[:-1].lower()
            matrix_lines = []

        elif line_stripped and line_stripped.startswith('[') and current_face:
            matrix_lines.append(line_stripped)

    if current_face and matrix_lines:
        matrix_str = ''.join(matrix_lines)
        parsed = parse_prolog_matrix(matrix_str)

        if parsed:
            faces_data[current_face] = parsed

    required = ['front', 'back', 'left', 'right', 'up', 'down']

    if all(face in faces_data for face in required):
        return faces_data

    return None


def run_temp_prolog_file(prolog_code, temp_filename):
    """Write Prolog code to a temporary file and execute it."""
    temp_query = os.path.join(PROLOG_DIR, temp_filename)

    try:
        with open(temp_query, 'w', encoding='utf-8') as f:
            f.write(prolog_code)

        result = subprocess.run(
            ['swipl', temp_query],
            capture_output=True,
            timeout=10,
            cwd=PROLOG_DIR
        )

        stdout = result.stdout.decode().strip()
        stderr = result.stderr.decode().strip()

        if stderr:
            print("Prolog stderr:")
            print(stderr)

        return stdout

    except subprocess.TimeoutExpired:
        print("Prolog timeout.")
        return ""

    except Exception as e:
        print(f"Error running Prolog temp file: {e}")
        return ""

    finally:
        try:
            os.remove(temp_query)
        except OSError:
            pass


# ============================================================================
# Q3D DATA EXTRACTION
# ============================================================================

def get_cube_data(obj_name):
    """Query Prolog for all 6 faces of an object."""
    faces = {}
    face_names = ['front', 'back', 'left', 'right', 'up', 'down']

    for face in face_names:
        query = (
            f":- consult('{Q3D_PROLOG_FILE}'), "
            f"view({face}, {obj_name}, _, _, M), "
            f"write(M), halt.\n"
        )

        output = query_prolog(query)

        if output:
            faces[face] = parse_prolog_matrix(output)
        else:
            faces[face] = None

    return faces


def extract_faces_from_q3d(obj_name, q3d_path=None):
    """Extract faces directly from q3d-ex.pl."""
    if q3d_path is None:
        q3d_path = Path(__file__).parent / Q3D_PROLOG_FILE

    text = q3d_path.read_text(encoding='utf-8', errors='replace')
    faces = {}

    pattern = re.compile(
        r"view\(\s*"
        r"(front|back|left|right|up|down)"
        r"\s*,\s*"
        + re.escape(obj_name)
        + r"\s*,\s*\d+\s*,\s*\d+\s*,\s*(\[\[.*?\]\])\s*\)\.",
        re.DOTALL
    )

    for match in pattern.finditer(text):
        face = match.group(1)
        matrix_str = match.group(2)
        faces[face] = parse_prolog_matrix(matrix_str)

    return {
        face: faces.get(face, None)
        for face in ['front', 'back', 'left', 'right', 'up', 'down']
    }


# ============================================================================
# DRAWING
# ============================================================================

def draw_cube_grid(faces, title='Cube Visualization', save_path=None):
    """
    Draw cube with 6 faces in 2D grid layout:

           [Up]
    [Left][Front][Right]
          [Down][Back]
    """
    fig, axes = plt.subplots(3, 3, figsize=(10, 10))
    fig.suptitle(title, fontsize=16, fontweight='bold')

    for row in axes:
        for ax in row:
            ax.set_visible(False)

    positions = {
        'up': (0, 1),
        'left': (1, 0),
        'front': (1, 1),
        'right': (1, 2),
        'down': (2, 1),
        'back': (2, 2),
    }

    for face_name, (row, col) in positions.items():
        if faces.get(face_name) is None:
            continue

        ax = axes[row, col]
        ax.set_visible(True)

        matrix = faces[face_name]
        rows = len(matrix)
        cols = len(matrix[0]) if matrix else 0

        ax.set_xlim(-0.5, cols - 0.5)
        ax.set_ylim(-0.5, rows - 0.5)
        ax.set_aspect('equal')
        ax.invert_yaxis()
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(face_name.upper(), fontweight='bold', fontsize=12)

        for r, row_data in enumerate(matrix):
            for c, value in enumerate(row_data):
                color = DEPTH_COLORS.get(value, '#FFFFFF')

                rect = Rectangle(
                    (c - 0.4, r - 0.4),
                    0.8,
                    0.8,
                    facecolor=color,
                    edgecolor='black',
                    linewidth=1.5
                )

                ax.add_patch(rect)

                ax.text(
                    c,
                    r,
                    value,
                    ha='center',
                    va='center',
                    fontsize=12,
                    fontweight='bold',
                    color='black'
                )

    legend_elements = [
        mpatches.Patch(
            facecolor=DEPTH_COLORS[key],
            edgecolor='black',
            label=DEPTH_LABELS[key]
        )
        for key in ['a', 'b', 'c', 'd', 'e', '*']
    ]

    fig.legend(
        handles=legend_elements,
        loc='upper center',
        bbox_to_anchor=(0.5, -0.02),
        ncol=6,
        fontsize=10
    )

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Saved: {save_path}")

    return fig


def draw_rotation_comparison(before_faces, after_faces, rotation_type, save_path=None):
    """Draw side-by-side before/after rotation comparison."""
    fig = plt.figure(figsize=(16, 8))

    fig.suptitle(
        f'Rotation: {rotation_type.replace("_", " ").title()} (QOR-Inspired)',
        fontsize=18,
        fontweight='bold',
        y=0.98
    )

    before_grid = fig.add_gridspec(
        3,
        3,
        left=0.05,
        right=0.45,
        top=0.9,
        bottom=0.05
    )

    after_grid = fig.add_gridspec(
        3,
        3,
        left=0.55,
        right=0.95,
        top=0.9,
        bottom=0.05
    )

    positions = {
        'up': (0, 1),
        'left': (1, 0),
        'front': (1, 1),
        'right': (1, 2),
        'down': (2, 1),
        'back': (2, 2),
    }

    ax_label = fig.add_axes([0.25, 0.93, 0.1, 0.03])
    ax_label.text(
        0.5,
        0.5,
        'BEFORE',
        fontsize=14,
        fontweight='bold',
        ha='center',
        va='center',
        transform=ax_label.transAxes
    )
    ax_label.set_visible(False)

    ax_label2 = fig.add_axes([0.75, 0.93, 0.1, 0.03])
    ax_label2.text(
        0.5,
        0.5,
        'AFTER',
        fontsize=14,
        fontweight='bold',
        ha='center',
        va='center',
        transform=ax_label2.transAxes
    )
    ax_label2.set_visible(False)

    def draw_faces_on_grid(face_dict, grid):
        for face_name, (row, col) in positions.items():
            if face_dict.get(face_name) is None:
                continue

            ax = fig.add_subplot(grid[row, col])

            matrix = face_dict[face_name]
            rows = len(matrix)
            cols = len(matrix[0]) if matrix else 0

            ax.set_xlim(-0.5, cols - 0.5)
            ax.set_ylim(-0.5, rows - 0.5)
            ax.set_aspect('equal')
            ax.invert_yaxis()
            ax.set_xticks([])
            ax.set_yticks([])
            ax.set_title(face_name.upper(), fontweight='bold', fontsize=10)

            for r, row_data in enumerate(matrix):
                for c, value in enumerate(row_data):
                    color = DEPTH_COLORS.get(value, '#FFFFFF')

                    rect = Rectangle(
                        (c - 0.4, r - 0.4),
                        0.8,
                        0.8,
                        facecolor=color,
                        edgecolor='black',
                        linewidth=1.5
                    )

                    ax.add_patch(rect)

                    ax.text(
                        c,
                        r,
                        value,
                        ha='center',
                        va='center',
                        fontsize=11,
                        fontweight='bold',
                        color='black'
                    )

    draw_faces_on_grid(before_faces, before_grid)
    draw_faces_on_grid(after_faces, after_grid)

    legend_elements = [
        mpatches.Patch(
            facecolor=DEPTH_COLORS[key],
            edgecolor='black',
            label=DEPTH_LABELS[key]
        )
        for key in ['a', 'b', 'c', 'd', 'e', '*']
    ]

    fig.legend(
        handles=legend_elements,
        loc='lower center',
        bbox_to_anchor=(0.5, -0.02),
        ncol=6,
        fontsize=10
    )

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Saved: {save_path}")

    return fig


# ============================================================================
# NORMAL ROTATION CALL
# ============================================================================

def apply_rotation_via_prolog(faces, rotation_type):
    """
    Call Prolog to apply normal cube rotation.

    Uses:
        apply_rotation_via_query/13
    """
    try:
        front_str = matrix_to_prolog(faces['front'])
        back_str = matrix_to_prolog(faces['back'])
        left_str = matrix_to_prolog(faces['left'])
        right_str = matrix_to_prolog(faces['right'])
        up_str = matrix_to_prolog(faces['up'])
        down_str = matrix_to_prolog(faces['down'])

        prolog_code = f"""
:- consult('{ROTATION_PROLOG_FILE}').

:- apply_rotation_via_query(
    {front_str},
    {back_str},
    {left_str},
    {right_str},
    {up_str},
    {down_str},
    {rotation_type},
    NF, NB, NL, NR, NU, ND),
   write_result(NF, NB, NL, NR, NU, ND),
   halt.
"""

        output = run_temp_prolog_file(
            prolog_code,
            '.temp_rotation_qor.pl'
        )

        parsed_faces = parse_faces_from_write_result(output)

        if parsed_faces:
            return parsed_faces

        print(f"Failed to parse rotation output for {rotation_type}")
        print(output)
        return faces

    except Exception as e:
        print(f"Error calling Prolog for {rotation_type}: {e}")
        return faces


# ============================================================================
# IN-PLANE ROTATION CALL — ONLY 1q AND -1q
# ============================================================================

def apply_in_plane_rotation(faces, in_plane_rotation):
    """
    Call Prolog to apply full 6-face in-plane rotation.

    Only supports:
        '1q'
        '-1q'

    Uses existing Prolog predicate:
        apply_in_plane_rotation_full/13
    """
    try:
        rotation = str(in_plane_rotation)

        if rotation not in {'1q', '-1q'}:
            print(f"Ignoring unsupported in-plane rotation: {rotation}")
            return faces

        front_str = matrix_to_prolog(faces['front'])
        back_str = matrix_to_prolog(faces['back'])
        left_str = matrix_to_prolog(faces['left'])
        right_str = matrix_to_prolog(faces['right'])
        up_str = matrix_to_prolog(faces['up'])
        down_str = matrix_to_prolog(faces['down'])

        prolog_code = f"""
:- consult('{ROTATION_PROLOG_FILE}').

:- apply_in_plane_rotation_full(
    {front_str},
    {back_str},
    {left_str},
    {right_str},
    {up_str},
    {down_str},
    '{rotation}',
    NF, NB, NL, NR, NU, ND),
   write_result(NF, NB, NL, NR, NU, ND),
   halt.
"""

        output = run_temp_prolog_file(
            prolog_code,
            '.temp_in_plane_rotation_qor.pl'
        )

        parsed_faces = parse_faces_from_write_result(output)

        if parsed_faces:
            return parsed_faces

        print(f"Failed to parse in-plane rotation output for {rotation}")
        print(output)
        return faces

    except Exception as e:
        print(f"Error executing Prolog for in-plane rotation {in_plane_rotation}: {e}")
        return faces


# ============================================================================
# DEMO DATA
# ============================================================================

def get_object1_faces():
    """Hardcoded Object 1 example from q3d-ex.pl."""
    return {
        'front': [
            ['c', 'c', '*'],
            ['b', 'a', 'c'],
            ['a', 'a', 'a']
        ],
        'back': [
            ['*', 'a', 'a'],
            ['a', 'a', 'a'],
            ['a', 'a', 'a']
        ],
        'left': [
            ['a', '*', '*'],
            ['a', 'a', 'b'],
            ['a', 'a', 'a']
        ],
        'right': [
            ['*', '*', 'b'],
            ['b', 'b', 'a'],
            ['a', 'a', 'a']
        ],
        'up': [
            ['a', 'a', 'b'],
            ['b', 'b', 'c'],
            ['c', 'b', 'c']
        ],
        'down': [
            ['a', 'a', 'a'],
            ['a', 'a', 'a'],
            ['a', 'a', 'a']
        ],
    }


# ============================================================================
# DEMOS
# ============================================================================

def demo_objects_from_q3d():
    """Demonstrate normal cube rotations using Prolog."""
    object1_faces = get_object1_faces()

    print("Generating static cube visualization...")

    fig = draw_cube_grid(
        object1_faces,
        'Object 1 - 3D Cube Views',
        'object1_cube_qor.png'
    )

    plt.close(fig)

    print("Generating normal rotations for Object 1...")

    rotations = [
        'towards_up',
        'towards_down',
        'towards_left',
        'towards_right'
    ]

    for rotation in rotations:
        print(f"  Computing Object 1 - {rotation}...")

        rotated_faces = apply_rotation_via_prolog(object1_faces, rotation)

        save_path = f'object1_rotation_{rotation}_qor.png'

        fig = draw_rotation_comparison(
            object1_faces,
            rotated_faces,
            rotation,
            save_path
        )

        plt.close(fig)


def demo_in_plane_rotations_from_q3d():
    """Demonstrate only 1q and -1q in-plane rotations."""
    object1_faces = get_object1_faces()

    print("Generating in-plane rotations for Object 1...")

    in_plane_rotations = ['1q', '-1q']

    for rotation in in_plane_rotations:
        print(f"  Computing Object 1 - in-plane rotation {rotation}...")

        rotated_faces = apply_in_plane_rotation(object1_faces, rotation)

        safe_rotation_name = rotation.replace('-', 'minus_')
        save_path = f'object1_in_plane_rotation_{safe_rotation_name}_qor.png'

        fig = draw_rotation_comparison(
            object1_faces,
            rotated_faces,
            f'in-plane {rotation}',
            save_path
        )

        plt.close(fig)


def render_objects_from_q3d(obj_names=None, output_dir=None):
    """Render static, normal rotations, and 1q/-1q in-plane rotations."""
    base = Path(__file__).parent

    if output_dir is None:
        output_dir = base / 'test_objects_qor'

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if obj_names is None:
        obj_names = [f'object{i}' for i in range(1, 8)]

    for obj in obj_names:
        print(f"Rendering {obj}...", end=' ', flush=True)

        faces = extract_faces_from_q3d(
            obj,
            q3d_path=base / Q3D_PROLOG_FILE
        )

        if not all(faces.values()):
            print('✗ missing faces')
            continue

        try:
            static_path = str(output_dir / f'{obj}_cube_qor.png')

            fig = draw_cube_grid(
                faces,
                f'{obj.upper()} - 3D Cube Views',
                static_path
            )

            plt.close(fig)

        except Exception as e:
            print(f"static failed: {e}")

        normal_rotations = [
            'towards_up',
            'towards_down',
            'towards_left',
            'towards_right'
        ]

        for rotation in normal_rotations:
            try:
                rotated_faces = apply_rotation_via_prolog(faces, rotation)

                save_path = str(
                    output_dir / f'{obj}_rotation_{rotation}_qor.png'
                )

                fig = draw_rotation_comparison(
                    faces,
                    rotated_faces,
                    rotation,
                    save_path
                )

                plt.close(fig)

            except Exception as e:
                print(f"{rotation} failed: {e}")

        in_plane_rotations = ['1q', '-1q']

        for rotation in in_plane_rotations:
            try:
                rotated_faces = apply_in_plane_rotation(faces, rotation)

                safe_rotation_name = rotation.replace('-', 'minus_')

                save_path = str(
                    output_dir / f'{obj}_in_plane_rotation_{safe_rotation_name}_qor.png'
                )

                fig = draw_rotation_comparison(
                    faces,
                    rotated_faces,
                    f'in-plane {rotation}',
                    save_path
                )

                plt.close(fig)

            except Exception as e:
                print(f"in-plane {rotation} failed: {e}")

        print('✓')


# ============================================================================
# MAIN
# ============================================================================

if __name__ == '__main__':
    print("=" * 60)
    print("PSVT:R Cube Visualization - QOR-Inspired Edition")
    print("=" * 60)
    print("Uses rotation_qor_inspired.pl with declarative rotation rules")
    print("In-plane rotations: only 1q and -1q")
    print()

    print("Running demo_objects_from_q3d...")
    demo_objects_from_q3d()

    print()
    print("Running demo_in_plane_rotations_from_q3d...")
    demo_in_plane_rotations_from_q3d()

    print()
    print("Visualization complete!")
    print()
    print("Generated PNG files:")
    print("  Static Cubes:")
    print("    - object1_cube_qor.png")
    print()
    print("  Normal Rotations for Object 1:")
    print("    - object1_rotation_towards_up_qor.png")
    print("    - object1_rotation_towards_down_qor.png")
    print("    - object1_rotation_towards_left_qor.png")
    print("    - object1_rotation_towards_right_qor.png")
    print()
    print("  In-Plane Rotations for Object 1:")
    print("    - object1_in_plane_rotation_1q_qor.png")
    print("    - object1_in_plane_rotation_minus_1q_qor.png")